GET http://localhost:3000/sales

###

POST http://localhost:3000/sales
Content-Type: application/json

{
    "item": "Michael",
    "price": 3,
    "quantity": 3
}

###

DELETE http://localhost:3000/sales/6369b5695de1058c67d26782